### ISSUE TITLE
Cant copy single items as "kiggelærer"

### ISSUE THREAD

**Issue by Mikkeljeppesen1** [praxisdigital/moodle-block_sharing_cart#102]
You cant copy a single item as "kiggelærer" because you dont have the permission to change anything on the course and therefore the copy to sharingcart icon dont appear.

Solution is to make a look a like to our copy section, but only for "kiggelærer". 

Please take some inspiration from my not so nice mockup ;) 

Note from niels brock. It schould be easy to see which item youre about to copy. So please consider having a large course with a lot of sections and activities. Maybe a 2 step. First select section and then a item. If youre not sure about the solution please contact me 

![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/42199572/979ad776-0d52-4b8c-9347-87670e545262)

**Comment by Mikkeljeppesen1** [comment]
after talking wiht umc and tk we have decided to give this a go. 

The extension to sharingcart block schould appear when you have the capability to manual take a backup of the course but arent allowed to edit the course

**Comment by AraPraxis** [comment]
## Enhancements
- Added "Copy activity" button to the block

## Testing
- Test that the extension only is shown, when the user with a role has the capability to backup activities, but NOT manage activities.
- Test that the new global setting works as expected (Should be able to hide the extension)


## Info
Branch: ara_GH-102_41
PR: https://github.com/praxisdigital/moodle-block_sharing_cart/pull/103
Moodle: 4.1+

**Comment by neeesn** [comment]
Testet on Mitnielsbrock test site, by adding kiggelærer to a course and see that the options to copy an activity appears as described.
Its working on kiggelærer as defined on Mitnielsbrock test site.

**Comment by Mikkeljeppesen1** [comment]
@AraPraxis which version can i use on our site. I can see there is a new version of sharingcart but only on the master branch

**Comment by AraPraxis** [comment]
Both branches will have "Kiggelærer" as a new feature;
MOODLE_41_STABLE v. 2023092000
master v. 2023110100

The difference is that someone have contributed to Donhinkelman's master branch (Some CSS updates)

**Comment by Mikkeljeppesen1** [comment]
Hi Anders,

I dont know if this is the right place to do it.

Niels brock asked for an update on this and we think we found a error: 
on this course (pxgrid) i can only copy from section 0 even if i go into another section and not in the root of the course: https://www.mitnielsbrock.dk/course/view.php?id=54003
on this course (onetopic) its seems to work as inteded. When im in the root i can copy from section 0 and when im go into another section i can copy the activity in the section  :https://www.mitnielsbrock.dk/course/view.php?id=49650

**Comment by AraPraxis** [comment]
## Fixed
- issue with activity copy button, where only activities from section 0 would be shown

## Testing
- Test that activities are shown, from the sections you're on


## Info
Branch: ara_GH-102_41
PR: https://github.com/praxisdigital/moodle-block_sharing_cart/pull/113
Moodle: 4.1


Branch: ara_GH-102_42
PR: https://github.com/praxisdigital/moodle-block_sharing_cart/pull/127/
Moodle: 4.2


Branch: ara_GH-102_master
PR: https://github.com/praxisdigital/moodle-block_sharing_cart/pull/114
Moodle: 4.1+
