### ISSUE TITLE
Sharing cart doesnt work on activities

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-block_sharing_cart#107]
On https://moodle.finansudd.dk/course/view.php?id=4244 if you login as kft@finansudd.dk - Kasper Finderup Tougård - you cannot add activities to the sharing card- But you can add sections - see this video: 
https://www.loom.com/share/f942933fefcd4a31ab737e5abaa90a62

I have looked at the capabilities on the role, but cant see which one i should be missing - if any - If its a missing capability, please let me know which. https://moodle.finansudd.dk/admin/roles/define.php?action=view&roleid=11

Hubspot: https://app-eu1.hubspot.com/contacts/25645903/record/0-5/2094477534

**Comment by frederikmillingpytlick** [comment]
**Capabilities which are checked in block_sharing_cart:**
- moodle/restore:restorecourse
- moodle/restore:restoreactivity
- moodle/backup:backupactivity
- moodle/course:manageactivities

**Specific for copying userdata:**
- moodle/backup:userinfo
- moodle/backup:anonymise
- moodle/restore:userinfo

**Comment by frederikmillingpytlick** [comment]
@neeesn It seems that the one he is missing is "moodle/course:manageactivities"

**Comment by frederikmillingpytlick** [comment]
> @frederikmillingpytlick Thank you, Can we add it to the readme file?

I've added it to https://github.com/praxisdigital/moodle-block_sharing_cart/issues/89
