### ISSUE TITLE
Bulk copy content into cart

### ISSUE THREAD

**Issue by AraPraxis** [praxisdigital/moodle-block_sharing_cart#108]
A feature to add multiple activities (like a select), and then add into the cart is a feature request from the users.
As written we probably need to update a lot of the JS to make everything run more smooth - The overall feature CSS/Styling of this should also be thought about..

https://github.com/donhinkelman/moodle-block_sharing_cart/issues/120

**Comment by mcardle** [comment]
This will not be implemented - closing
