### ISSUE TITLE
Unable to delete items in cart

### ISSUE THREAD

**Issue by AraPraxis** [praxisdigital/moodle-block_sharing_cart#110]
Users can't delete items. Not a lot of info is given, other than the labels probably has an issue as well?
https://github.com/donhinkelman/moodle-block_sharing_cart/issues/173

**Comment by AraPraxis** [comment]
Hello @cbrherms,

We have not yet had the time to look at the issue, but we'll try to look into it as fast as possible -
Is it specifically labels that cannot be removed, or any type of module/activity?

If possible a short video of the issue would be appreciated, or if an error occurs a picture of it. So we can try an recreate the error and make a possible fix :)

Kind regards,
Anders Rasmussen

Moxis Team

**Comment by mcardle** [comment]
New reworked Sharing Cart - closing.
