### ISSUE TITLE
Error on nielsbrock when pasting a h5p item from sharing cart into a course

### ISSUE THREAD

**Issue by superfoght** [praxisdigital/moodle-block_sharing_cart#111]
`dml_write_exception: Error writing to database (Duplicate entry '0-2626250' for key 'mdl_course_modules_viewed.mdl_courmoduview_usecou_uix'
INSERT INTO mdl_course_modules_viewed (userid,timecreated,coursemoduleid) VALUES(?,?,?)
[array (
  0 =&gt; 0,
  1 =&gt; '1673015422',
  2 =&gt; 2626250,
)]) in [dirroot]/lib/dml/moodle_database.php:497
Stack trace:
#0 [dirroot]/lib/dml/moodle_read_slave_trait.php(293): moodle_database-&gt;query_end(false)
#1 [dirroot]/lib/dml/mysqli_native_moodle_database.php(1459): mysqli_native_moodle_database-&gt;query_end(false)
#2 [dirroot]/lib/dml/mysqli_native_moodle_database.php(1505): mysqli_native_moodle_database-&gt;insert_record_raw('course_modules_...', Array, true, false)
#3 [dirroot]/backup/moodle2/restore_stepslib.php(4806): mysqli_native_moodle_database-&gt;insert_record('course_modules_...', Array)
#4 [dirroot]/backup/util/plan/restore_structure_step.class.php(137): restore_userscompletion_structure_step-&gt;process_completionview(Object(stdClass))
#5 [dirroot]/backup/util/helper/restore_structure_parser_processor.class.php(123): restore_structure_step-&gt;process(Array)
#6 [dirroot]/backup/util/xml/parser/processors/grouped_parser_processor.class.php(178): restore_structure_parser_processor-&gt;dispatch_chunk(Array)
#7 [dirroot]/backup/util/helper/restore_structure_parser_processor.class.php(111): grouped_parser_processor-&gt;postprocess_chunk(Array)
#8 [dirroot]/backup/util/xml/parser/processors/simplified_parser_processor.class.php(148): restore_structure_parser_processor-&gt;postprocess_chunk(Array)
#9 [dirroot]/backup/util/xml/parser/processors/progressive_parser_processor.class.php(92): simplified_parser_processor-&gt;process_chunk(Array)
#10 [dirroot]/backup/util/xml/parser/progressive_parser.class.php(189): progressive_parser_processor-&gt;receive_chunk(Array)
#11 [dirroot]/backup/util/xml/parser/progressive_parser.class.php(277): progressive_parser-&gt;publish(Array)
#12 [internal function]: progressive_parser-&gt;end_tag(Object(XMLParser), 'completionview')
#13 [dirroot]/backup/util/xml/parser/progressive_parser.class.php(178): xml_parse(Object(XMLParser), '&lt;?xml version="...', true)
#14 [dirroot]/backup/util/xml/parser/progressive_parser.class.php(157): progressive_parser-&gt;parse('&lt;?xml version="...', true)
#15 [dirroot]/backup/util/plan/restore_structure_step.class.php(110): progressive_parser-&gt;process()
#16 [dirroot]/backup/util/plan/base_task.class.php(186): restore_structure_step-&gt;execute()
#17 [dirroot]/backup/moodle2/restore_activity_task.class.php(224): base_task-&gt;execute()
#18 [dirroot]/backup/util/plan/base_plan.class.php(191): restore_activity_task-&gt;execute()
#19 [dirroot]/backup/util/plan/restore_plan.class.php(168): base_plan-&gt;execute()
#20 [dirroot]/backup/controller/restore_controller.class.php(411): restore_plan-&gt;execute()
#21 [dirroot]/blocks/sharing_cart/classes/controller.php(559): restore_controller-&gt;execute_plan()
#22 [dirroot]/blocks/sharing_cart/restore.php(90): block_sharing_cart\controller-&gt;restore('404040', 49650, 1)
#23 {main}
`

**Comment by mcardle** [comment]
It is a duplicate index issue - we probably need another identifier in the index

**Comment by sampraxis** [comment]
@superfoght 
This issue is ready for testing.
https://github.com/praxisdigital/moodle-block_sharing_cart/pull/112
