### ISSUE TITLE
Backed up user data

### ISSUE THREAD

**Issue by AraPraxis** [praxisdigital/moodle-block_sharing_cart#115]
The user is saying that when backing up an activity the activity completion is not added -
https://github.com/donhinkelman/moodle-block_sharing_cart/issues/176

**Comment by AraPraxis** [comment]
Awaiting the user to answer a question on the issue

**Comment by sampraxis** [comment]
@AraPraxis 
I don't think that sharing cart doesn't include user completion when you try to copy an activity to the block
https://github.com/donhinkelman/moodle-block_sharing_cart/blob/7545baa10bf9668485b3e8b08efc20356cc01e40/classes/controller.php#L242
