### ISSUE TITLE
Session lock when copy to sharing cart

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-block_sharing_cart#117]
On Mitnielsbrock the users still get this error when using the sharing cart:

![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/1931926/caf7a223-9b4e-4e0c-a410-e7ca4c5f84f6)

I as admin cannot reproduce the error.

From the ticket
En bruger(achr) forklarer at det tager meget lang til at kopiere nedenstående sektion til Delekurven.
Når jeg forsøger at kopier samme sektion, https://www.mitnielsbrock.dk/course/view.php?id=49202&section=1--> så når systemet også at time ud, dog får jeg Sektionen fint over i min Delekurv.

Jeg gætter på , at det er dette objekt https://www.mitnielsbrock.dk/mod/folder/view.php?id=2627453 der laver ravage, pga. Indholdet med special tegn, grafik og video m.m. ?

https://app-eu1.hubspot.com/contacts/25645903/record/0-5/2144522208

**Comment by sampraxis** [comment]
Related issue: #118
