### ISSUE TITLE
Performance issue when copy an item to sharing with a site with large database

### ISSUE THREAD

**Issue by sampraxis** [praxisdigital/moodle-block_sharing_cart#118]
Solution:
Move the business logic to the an adhoc task.

Related issues:
praxisdigital/moodle-block_sharing_cart#105
praxisdigital/moodle-block_sharing_cart#117

```[tasklist]
### Tasks
- [ ] https://github.com/praxisdigital/moodle-block_sharing_cart/issues/119
```

**Comment by sampraxis** [comment]
Ready for testing.
## Notes before testing
 * There has been added new admin setting for switching backup/restore mode between "immediate" and "asynchronous".
 * Issue #119 fix has been added to this change. When you testing #118, you have to test #119 as well.
 * In upgrade.php I have added a cleanup script that will remove any sharing cart item that doesn't have a backup file.

## Test instructions for #118 
### Test backup: asynchronous without user data.
1. Set setting ``block_sharing_cart/backup_mode`` to "Asynchronous". 
2. Set setting ``block_sharing_cart/restore_mode`` to "Asynchronous".
3. Create a new course or reuse one of the courses (Course A).
4. Add block_sharing_cart.
5. Create a new course module or reuse one of the course modules.
6. Copy a course module from a course to sharing cart.
7. Expect sharing cart item text to be muted (grey or lighter color) and ``Copy to course`` to be hidden (If ad hoc task happens to run instantly, the button be appear in the item).
8. Wait till ad hoc task (``block_sharing_cart_async_backup_course_module``) is completed or run it manually ``/admin/tool/task/adhoctasks.php``
9. Create a new course (Course B).
10. Add block_sharing_cart to the new course.
11. Press ``Copy to course`` button and place it into the course.
12. Expect item not to be appear instantly.
13. See if ad hoc task (``block_sharing_cart_async_restore_course_module``) is still in the queue. If it is, run it manually in ``/admin/tool/task/adhoctasks.php``.
14. Go back the course or reload the course page (Course B).
15. Expect the item that has been copied appear in the course (Course B).

**Comment by neeesn** [comment]
1. Når man kopiere en sektion til delekurven skal den være grå, så man kan se den kopiere hele sektionen ud. Lige ny er det kun aktiviteterne i sektionen der er grå, når den åbnes i delekurven, når der kopieres. 
![image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/1931926/ebb11e03-9cc3-472c-9c90-9b51216c1032)

2. Den skal lytte på hvornår den er færdig med at kopiere og ændre farven fra grå til sort, ellers vil nogle kunder sidde og vente meget længe.

3. Når man indsætter asynkront skal der komme en besked om at man er ved at kopiere data ind i kurset fra delekurven. Der er ingen indikator på dette nu.  
4. Kommer man til at kopiere samme sektion ind i kurven ser det ud til der er en CSS fejl og den nummerere de kommente kopier forkert. 
![image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/1931926/883aa624-c6ff-4172-8f06-743f9344dd1b)

**Comment by sampraxis** [comment]
We have an issue in upgrade progress.
When sharing cart record content user id that is no longer exists in the system, it cause upgrade to failed.

**Comment by sampraxis** [comment]
Plan on release to Niels Brock today @ 16:00
