### ISSUE TITLE
Problem with too much content in labels

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-block_sharing_cart#119]
If you copy a label to sharing cart, it shows the complete content of the label. 
This means that the sharing cart is very very long. 
See this screencast from Mitnielsbrock: https://nielsbrock.screencasthost.com/watch/cZVf6OVHpfz
it also shows some CSS error in the buttons in the sharing cart, where the text changes. 

Hubspot: https://app-eu1.hubspot.com/contacts/25645903/record/0-5/2038978767

## TODO
- [x] Limit characters of the mod_label.
- [x] Remove deprecated functions.

**Comment by sampraxis** [comment]
@neeesn The changes of this issue is merged to #118 
You can test it with that version
