### ISSUE TITLE
Cant insert copied item from sharing cart

### ISSUE THREAD

**Issue by Mikkeljeppesen1** [praxisdigital/moodle-block_sharing_cart#134]
Specific issue on following course: https://moodle.zbc.dk/course/view.php?id=61440

If you try so copy the section of "æg og pasta retter" it will appear after a while in the sharing cart but i dont get the option to insert it again at all. It is kind of disabled and i cant even insert the section anywhere else:

![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/42199572/913e0065-1a5b-4522-9c12-cd88a8e1cc34)

Ive tried to make a simple setup and can confirm that it is not because there is sections in a sections. 

I dont know if it has anything to do with the case: but in the drop down of the sections all the listed sections seems a bit weird:

![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/42199572/3b56e435-809e-42ef-b7cb-f2f74076fe64)

**Comment by mcardle** [comment]
We are rewriting the whole sharing cart right now and making it a lot better. We are not fixing any issue in the current one right now, but maybe have a chat with @frederikmillingpytlick about the progress.

**Comment by mcardle** [comment]
@Mikkeljeppesen1

**Comment by Mikkeljeppesen1** [comment]
Soooorry, will look at this tomorrow

**Comment by superfoght** [comment]
@Mikkeljeppesen1 this is because the section is empty (doesn't contain any activities). It only contains subsections that cannot be copied with the sharing cart anyways.

The error is that the sharing cart icon is displayed on empty sections.

**Comment by superfoght** [comment]
@Mikkeljeppesen1 this should be done now too. There is a warning for when you copy empty sections. I will close the issue.
