### ISSUE TITLE
Sharing cart icon appear when sections are empty

### ISSUE THREAD

**Issue by superfoght** [praxisdigital/moodle-block_sharing_cart#136]
There is a limitation on the sharing cart, that you can't copy and insert 'empty' sections with no activities.

However, the sharing cart icon still appear on the sections that have no activites. And you are actually able to copy them - but you can't insert them from the sharing cart

I think we should remove the icon when it's not possible to copy the section.

https://app-eu1.hubspot.com/contacts/25645903/record/0-5/2814558942

**Comment by frederikmillingpytlick** [comment]
Fixed in #133

**Comment by superfoght** [comment]
@frederikmillingpytlick I'll close this. I gave my feedback regarding this in #133
