### ISSUE TITLE
Errors in ad-hoc tasks regarding sharingcart, on DBU

### ISSUE THREAD

**Issue by superfoght** [praxisdigital/moodle-block_sharing_cart#140]
There is errors in the list in ad-hoc tasks. And when I run them, I get this error: 

![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/2778015/f635ca08-d70d-485e-b60f-9bc8381eb893)

**Comment by Mikkeljeppesen1** [comment]
Just want to add that every plugins is up 2 date on the site.

Other site with the improved sharingcart dont seems to have this issue

**Comment by frederikmillingpytlick** [comment]
These were the old sharing cart tasks which are now unable to run.

I've removed them. They should no longer be able to appear. Closing issue.
