### ISSUE TITLE
Copying a section into topics format, or other formats, does not overwrite the section title.

### ISSUE THREAD

**Issue by superfoght** [praxisdigital/moodle-block_sharing_cart#143]
Steps to reproduce

1. Open a course in topic format or other formats beside pxgrid
2. Copy a section with a title that has been renamed (that is, it should not be the default title such as section 1, section 2 etc.), to the sharing cart
3. Copy the section FROM the sharing cart into a section in the course. 
4. Check if the title is overwritten

**Comment by sampraxis** [comment]
@superfoght 
The section seems to be overwrite correctly already when you refresh the page.

The issue might be in reactive component issue itself that doesn't obtain correct data (it might obtain the previous just right before the restore process is finished).

**Comment by superfoght** [comment]
> @superfoght The section seems to be overwrite correctly already when you refresh the page.
> 
> The issue might be in reactive component issue itself that doesn't obtain correct data (it might obtain the previous just right before the restore process is finished).

That's correct. I didn't see that.

Can we fix this?

**Comment by sampraxis** [comment]
> > @superfoght The section seems to be overwrite correctly already when you refresh the page.
> > The issue might be in reactive component issue itself that doesn't obtain correct data (it might obtain the previous just right before the restore process is finished).
> 
> That's correct. I didn't see that.
> 
> Can we fix this?

Yes, it's possible to fix it.

**Comment by sampraxis** [comment]
We found out that this is a core issue.
Moodle core reactive doesn't work properly after we trigger the section state change.
It cause the section title in the side menu to the left to become undefined and the title of section is still the same, even the web service that response with the state of section returns the latest data (With the title that has been changed).

Confirmed this issue with @frederikmillingpytlick

**Comment by superfoght** [comment]
Discussed this with @TubsDK 

@frederikmillingpytlick @sampraxis we would like to display a warning message in the block after the section has been copied, saying something like "The section is copied. If you don't see all changes, please refresh your browser".

**Comment by frederikmillingpytlick** [comment]
Test with #144 & #145

**Comment by superfoght** [comment]
NICE!
