### ISSUE TITLE
Restoring single activity from section backup imports the whole section

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-block_sharing_cart#144]
Nielsbrock has testet in onetopic and found an error.
If you copy a whole section to sharing car, Then in the sharing cart open the section and copy only one activity into a section, it copies the whole section. 

I have recreated the error: https://go.screenpal.com/watch/cZ1FiaVNMwH

Test course on mitnielsbrock test site: https://mitnielsbrock-dk.moodle.moxis.dk/course/view.php?id=44374
Hubspot: https://app-eu1.hubspot.com/contacts/25645903/record/0-5/3142049503

**Comment by neeesn** [comment]
I have updated oneTopic to the newest version, and theres still the same error.

**Comment by neeesn** [comment]
You cannot copy whole sections from onetopic to sharing cart and the "basket" icon is missing on the sections

**Comment by frederikmillingpytlick** [comment]
Test with #143 & #145
