### ISSUE TITLE
Missing option to choose and copy section

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-block_sharing_cart#145]
The sharing cart is missing the option to choose a section via a dropdown to copy. This has been used before by Mitnielsbroc, to copy sections in the onetopic format. 

![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/1931926/7070259b-8a40-46c4-887e-1365fa246d29)

Hubspot: https://app-eu1.hubspot.com/contacts/25645903/record/0-5/3142049503

**Comment by mcardle** [comment]
It should be a setting if you want to display the dropdown.

The new design is very clean and it should be optional to enable that feature.

**Comment by frederikmillingpytlick** [comment]
Test with #143 & #144
