### ISSUE TITLE
Use language strings from withing the block

### ISSUE THREAD

**Issue by superfoght** [praxisdigital/moodle-block_sharing_cart#150]
When you copy to the sharing cart, the following modal appear:
![image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/2778015/8f348330-1475-475e-acf1-258c663a05c2)

The primary button uses the 'backup' language string from the core. It should use the language string from the block:
https://github.com/praxisdigital/moodle-block_sharing_cart/blob/3a23ce7ca56236792002bca7465c527868d5663e/amd/src/app/block/element.js#L374

                key: 'backup',
                component: 'core',

to 

                key: 'backup',
                component: 'block_sharing_cart',

**Comment by frederikmillingpytlick** [comment]
@superfoght fixed in latest version of sharing cart: 2024032114
