### ISSUE TITLE
Problem with disabled activities

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-block_sharing_cart#156]
**Describe the bug**

A red ! mark is set in front of the section copied. It seems to mark the section with an error, but there is no error description. 
We found out that a assignment of big blue button had been added to the course, but then later disabled. 
This marks the section as error. 
I have made a video here: https://go.screenpal.com/watch/cZiv6sVPHES

**To Reproduce**
https://go.screenpal.com/watch/cZiv6sVPHES

**Current behavior**
When copieng to the sharing cart, the section is marked with an ! error

**Expected behavior**
The section is copied to the sharing cart, without the disabled activities.

**Screenshots/videos**
https://go.screenpal.com/watch/cZiv6sVPHES

Test can be made here: https://kundeteam.moodle.moxis.dk/course/view.php?id=10&sectionid=79

**Comment by frederikmillingpytlick** [comment]
@neeesn ready for testing :)

I decided not to group more sharing cart issues into this, since some of them require more advanced error logging, which I've introduced in this as well.
