### ISSUE TITLE
Cant drag into sharing cart in oneTopic Section 0

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-block_sharing_cart#163]
**Describe the bug**
When in tab format and the setting "Visualization mode of section 0" is set to "Before the tabs" the sharing cart aint working. You cant pull into the cart and the cart icon is missing

**To Reproduce**
1. Go to https://www.mitnielsbrock.dk/
2. Create a new course in with one topics as format
3. Set "Visualization mode of section 0" is set to "Before the tabs" in the settings 
4. Insert an assignment in section 0
5. Insert the sharing cart
6. Drag the assignement to the sharing cart

**Current behavior**
Nothing happens - icon is missing and you cant dragg to cart
**Expected behavior**
That the icon is present at the activity and that it can be dragged into the ahsring cart

**Screenshots/videos**
https://www.mitnielsbrock.dk/course/view.php?id=56096
https://www.mitnielsbrock.dk/course/view.php?id=63099

**Ticket link**
https://app-eu1.hubspot.com/contacts/25645903/record/0-5/3803173366

**Comment by frederikmillingpytlick** [comment]
@neeesn 

This is an error in "visualization mode of section 0" when it is set to "Before the tabs" inside the format_onetopic.

We can't fix this in the sharing cart. However dragging from the course index drawer should still work :)
