### ISSUE TITLE
Drag and drop feature dosent work on moodle 4.4

### ISSUE THREAD

**Issue by Mikkeljeppesen1** [praxisdigital/moodle-block_sharing_cart#164]
**Describe the bug**
Youre not able to drag and drop sections into the sharing cart on moodle 4.4 with the newest version of sharing cart

**To Reproduce**
1. Create course + sections with activities
2. Try to drag sections into sharingcart
4. Drop and nothing happens

**Ticket link**
(https://app-eu1.hubspot.com/contacts/25645903/record/0-5/3810349815?interaction=note)

**Comment by frederikmillingpytlick** [comment]
Ready for testing @Mikkeljeppesen1 

We can't make it so you can drag & drop the section title in the top of the page. But I've refactored it to now support the course index drawer as well as pxgrid section cards.

**Comment by Mikkeljeppesen1** [comment]
@frederikmillingpytlick 

sorry for a test-delay. 

When im trying to drag a section from the drawer and into the sharing cart i think i get an error. Is that perceived correctly? i cant hover on the icon and get a tool tip.


![Image](https://github.com/user-attachments/assets/3ba6aec1-dc1f-42a1-a757-11f031218fe2)

**Comment by frederikmillingpytlick** [comment]
@Mikkeljeppesen1 Yes, that means the backup adhoc task failed. Which site did you test on? If we find the task logs, we can figure out what is happening :)

**Comment by Mikkeljeppesen1** [comment]
@frederikmillingpytlick https://moodlefourfour.branch.moxis.dk/course/view.php?id=2

**Comment by frederikmillingpytlick** [comment]
The error log show the following:
```log
Execute adhoc task: block_sharing_cart\task\asynchronous_backup_task
Adhoc task id: 22
Adhoc task custom data: {"backupid":"9535f2cc548d6348707b427811310eff","item":{"id":8,"user_id":2,"file_id":null,"parent_item_id":null,"old_instance_id":8,"type":"section","name":"Den kreative reklame","status":0,"sortorder":null,"timecreated":1725948911,"timemodified":1725948911},"backup_settings":{"users":false,"anonymize":false}}
... started 07:15:42. Current memory use 7.7 MB.
Processing asynchronous backup for backup: 9535f2cc548d6348707b427811310eff
Executing before_backup_started_hook...
Excluding activities which are disabled on the site...
...Including activity: (id: 11)
...Including activity: (id: 12)
...Including activity: (id: 65)
...Including activity: (id: 64)
...Including activity: (id: 13)
...Including activity: (id: 14)
...Including activity: (id: 15)
...Including activity: (id: 16)
...Including activity: (id: 67)
Executing before_backup_started_hook completed, continuing with backup...
Can't find data record in database table course.
#0 /var/www/html/moodle/lib/dml/moodle_database.php(1635): moodle_database->get_record_select()
#1 /var/www/html/moodle/lib/classes/context/course.php(200): moodle_database->get_record()
#2 /var/www/html/moodle/backup/util/helper/async_helper.class.php(147): core\context\course::instance()
#3 /var/www/html/moodle/backup/util/helper/async_helper.class.php(129): async_helper->get_resource_link()
#4 [internal function]: async_helper->lookup_message_variables()
#5 /var/www/html/moodle/backup/util/helper/async_helper.class.php(171): preg_replace_callback()
#6 /var/www/html/moodle/blocks/sharing_cart/classes/task/asynchronous_backup_task.php(74): async_helper->send_message()
#7 /var/www/html/moodle/lib/classes/cron.php(519): block_sharing_cart\task\asynchronous_backup_task->execute()
#8 /var/www/html/moodle/lib/classes/cron.php(348): core\cron::run_inner_adhoc_task()
#9 /var/www/html/moodle/admin/cli/adhoc_task.php(148): core\cron::run_adhoc_task()
#10 {main}
Async backup failed, trying to set item status to failed...
Async backup failed, item status has been set to failed, aborting...
... used 563 dbqueries
... used 2.049880027771 seconds
Adhoc task complete: block_sharing_cart\task\asynchronous_backup_task
```

It's an error that occurs if you have the following setting enabled:
![image](https://github.com/user-attachments/assets/d28a15d0-6794-4f70-b36b-a4f466110e28)

That's a known issue in Moodle core. We have created a tracker issue on it. 

@Mikkeljeppesen1 Try testing again with it disabled :)

**Comment by Mikkeljeppesen1** [comment]
@frederikmillingpytlick hate myself for that one. Well anyway - its now tested and approved ;)

**Comment by frederikmillingpytlick** [comment]
> @frederikmillingpytlick hate myself for that one. Well anyway - its now tested and approved ;)

Thanks @Mikkeljeppesen1, don't be so harsh on yourself :sweat_smile:
