### ISSUE TITLE
new feature: mark all when you bulk delete

### ISSUE THREAD

**Issue by Mikkeljeppesen1** [praxisdigital/moodle-block_sharing_cart#168]
Feature request approved with low priority by TK:

If you have a lot of items in the sharing cart and you want to delete them all, its annoying to mark them all - one by one. Make a "mark all" button/select, that would speed up the process

![Image](https://github.com/user-attachments/assets/f43b014c-d3af-4e8b-9872-9350a488c4ba)

**Comment by frederikmillingpytlick** [comment]
Fixed, closing
