### ISSUE TITLE
Rybners: Still trying to add to sharing cart

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-block_sharing_cart#174]
Jørgen has a problem with coping to / from sharing cart.

From the ticket:

_I've placed 2 files/tests in my shared cart in this test room Edit course: Jørgen's test room | Moodle.
And I have been able to put in one file but the other is waiting see green arrow._

![Image](https://github.com/user-attachments/assets/fc78d57b-7051-4006-bea0-0bfb0d862179)
_The lower green arrow is the file, and as you can see by the other green arrow it's queuing under copies, but nothing else happens, so please check if you can see anything, and if you can, write if there's anything I can do to stop a copying process._

And today:
_I just checked today, and I can see that it hasn't completed the task. I know that Merete (SUN) also had a problem, which resolved itself overnight 😊. It could also be that file, but I've seen a few cases where when they try to put in a file, the copying runs for a long time and they refresh the screen several times, and then all of a sudden, it's there._

I cant login as Jørgen as he is a admin, i have tried to copy the same section and doesnt get any problems. 
Can you see anything in the DB or chace or something like that? The crons seems to be running and the adhocs as well.

Hubspot: https://app-eu1.hubspot.com/help-desk/25645903/view/265930994/ticket/28764859590/thread/8674326760#email

**Comment by frederikmillingpytlick** [comment]
@neeesn there is a new version of the sharing cart available, however it wasn't automatically created in morris.

I created it manually, try updating to that one and see if the issue still persists

**Comment by frederikmillingpytlick** [comment]
merged with other issues into one see: https://github.com/praxisdigital/moodle-opgaver/issues/523
