### ISSUE TITLE
Sharing quiz HEG

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-block_sharing_cart#176]
**Describe the bug**
When trying to copy **Geometri (rumfang) 1**   from https://yourspace.erhvervsskolerne.dk/course/view.php?id=1012

**To Reproduce**
1. Go to https://yourspace.erhvervsskolerne.dk/course/view.php?
2. Copy Geometri (rumfang) 1 to sharing cart
3. create a course
4. insert Geometri (rumfang) 1 from sharing cart

**Current behavior**
It is trying and shows its loading - been like that for 2 hours-.

**Expected behavior**
That the quiz is copied

**Screenshots/videos**
![Image](https://github.com/user-attachments/assets/0c465b76-26ff-4f2d-9a19-bd97be2a5f8e)
![Image](https://github.com/user-attachments/assets/84c78aba-c633-42de-ad81-2dd238bfb72d)

Hubspot: https://app-eu1.hubspot.com/help-desk/25645903/view/265930994/ticket/29740064996/thread/8677809342#email

**Ticket link**
Add a link to the HubSpot ticket 

**Related issues**

**Comment by frederikmillingpytlick** [comment]
@neeesn just like the rybners issue, try to install the newest version of the sharing cart and see if it fixes the issue

**Comment by frederikmillingpytlick** [comment]
Merged with other issues into one see: https://github.com/praxisdigital/moodle-opgaver/issues/523
