### ISSUE TITLE
block_sharingcart - dropzone

### ISSUE THREAD

**Issue by AraPraxis** [praxisdigital/moodle-block_sharing_cart#63]
@mcardle commented on [Fri Aug 19 2022](https://github.com/praxisdigital/moodle-opgaver/issues/156)

The block_sharingcart icons does not fit in the

**Comment by AraPraxis** [comment]
The changes are approved but I'm awaiting a push for format_pxgrid in 40 before testing, since sharingcart does not work in pxgrid at the moment

**Comment by AraPraxis** [comment]
### Added..
- Activities and sections can now be dragged and dropped into the sharing cart block
- Added basket icon in footer

### Test..
-  That the drag and drop function works as intended
- You should be able to drag and drop any activity/section and place it into the sharing cart block.
- You should be able to drag and drop any activity/section and place it into the basket icon that pops up in the footer
If you use theme_pxbase, then a basked icon will pop up over the question mark icon in the footer.
If you use boost, the basket icon will overlap (be put on top of) the question mark icon in the footer.
If you use classic an icon will not appear, but you can still drag and drop into the block.

Branch: ara_ZH_40
Pull: https://github.com/praxisdigital/moodle-block_sharing_cart/tree/ara_ZH_40

**REMEMBER TO PULL format_pxgrid 40 ALSO! TO MAKE SURE IT WORKS IN PXGRID AS WELL AS THE NORMAL FORMAT**
**MINIMUM VERSION ON format_pxgrid SHOULD BE : 2022090700**

**Comment by superfoght** [comment]
@AraPraxis I tested this in the topics format. I couldn't see the icon above the question mark?
also the alignment is a bit off on the sharing cart icon
![image.png](https://images.zenhubusercontent.com/61fb94a8e26aff511b3cf27c/2a190c09-3a97-4bb9-9928-a8422b2be796)

**Comment by AraPraxis** [comment]
@superfoght If you're testing on a local site, it might be because of theme_pxbase is not updated? (Atleast when it comes to the basket placement)

And it's my mistake with the drag and drop -
A new feature is added where you have to choose between 'drag and drop' or 'click to add'

Can be found under Site admin -> Plugins -> Blocks -> Sharing cart

**Comment by AraPraxis** [comment]
If you don't use theme_pxbase then the basket icon will pop up over the question mark

**Comment by superfoght** [comment]
@AraPraxis testing is done. But I can't merge due to a conflict

**Comment by AraPraxis** [comment]
Donhinkelmnn have made an update, I'll pull, merge into our branch and give this to release :)

**Comment by AraPraxis** [comment]
## RELEASE

MOODLE_40_STABLE
Version: 2022091401
