### ISSUE TITLE
Create hook for additional backup

### ISSUE THREAD

**Issue by mcardle** [praxisdigital/moodle-block_sharing_cart#65]
We need an additional backup method to be run for us to backup images for pxgrid. For this to be a general thing it should be done with Moodle event system.

We should register one event per backup method and one per restore method.

See: https://docs.moodle.org/dev/Events_API

**Comment by frederikmillingpytlick** [comment]
3.11 PR: https://github.com/praxisdigital/moodle-block_sharing_cart/pull/66

4.0 PR: https://github.com/praxisdigital/moodle-block_sharing_cart/pull/67

**Comment by frederikmillingpytlick** [comment]
Will be tested together with https://github.com/praxisdigital/format__pxgrid/issues/105

**Comment by superfoght** [comment]
@frederikmillingpytlick  I have tested for 4.0 and it works. I cant merge the PR.
