### ISSUE TITLE
Sharing cart not copying assignments when copying userdata

### ISSUE THREAD

**Issue by superfoght** [praxisdigital/moodle-block_sharing_cart#69]
I tested on a site, when copying an assignment activity and then copying it into another course with the same participants enrolled.. It did not copy their submissions along..

**Comment by mcardle** [comment]
It should ask if you want to copy userdata, if selected it should copy enrolments. If not selected it should not.

**Comment by AraPraxis** [comment]
It's not possible for the sharing cart to copy the submissions along - The plugin is only made as an easy copy & paste for acitivties/modules and sections.
It only asks if you want to copy data, if you try to copy specific activities or sections with those activities (Forums, File sharings, etc.).

Closing issue.
