### ISSUE TITLE
Mitnielsbrock - Error in sharingCart No userdata is copied.

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-block_sharing_cart#71]
The error reported is:
_If you copy some activities with Sharingcart, the userdata is not included. Try copy a journal with sharingcart and in the popup marks that you want to copy usersdata, it doesnt. 
When the journal is inserted, again, its without userdata._ 

Small video that shows the problem: https://www.loom.com/share/aaaaf62314ed4b4aa0889a9fa8437c0c

**Comment by neeesn** [comment]
Tested in https://mitnielsbrock-dk-morris.moodle.praxis.dk/course/view.php?id=52887

**Comment by frederikmillingpytlick** [comment]
This issue occurs, because the sharing cart by default anonymizes the userdata in its backups if you have the "moodle/backup:anonymise" capability.

**Comment by frederikmillingpytlick** [comment]
Ready for testing

[fmp_GH-71_40](https://github.com/praxisdigital/moodle-block_sharing_cart/pull/72)

**Comment by frederikmillingpytlick** [comment]
@superfoght Sorry i missed that, I've backported to 3.11 and 3.11

> Ready for testing
> 
> [fmp_GH-71_40](https://github.com/praxisdigital/moodle-block_sharing_cart/pull/72)
> [fmp_GH-71_311](https://github.com/praxisdigital/moodle-block_sharing_cart/pull/75)
> [fmp_GH-71_310](https://github.com/praxisdigital/moodle-block_sharing_cart/pull/76)

**Comment by neeesn** [comment]
I have testet and it working. But i cant merge 3.11 and 4 branch beacause of conflict.
![image.png](https://images.zenhubusercontent.com/61f3b1064ed5f55493376dfb/99fdcfd1-fb66-4174-9504-5486c3eed212)

Can you please solve it

**Comment by frederikmillingpytlick** [comment]
I've solved and merged the commits into both our fork and the sharing cart repo

**Comment by frederikmillingpytlick** [comment]
Ready for release @Mikkeljeppesen1
