### ISSUE TITLE
Backup icon missing for teacher (shoppingcart)

### ISSUE THREAD

**Issue by DKSteffensen** [praxisdigital/moodle-block_sharing_cart#73]
On techcollege an issue with sharing cart has appeared when a teacher wants to backup an activity from a course he is not enrolled in.

The teacher do have editing rights, and can also insert from the sharing cart.
In a course where the teacher is enrolled, it works flawlesly.

Admins can backup activities everywhere.

Course to test in:
https://moodle.techcollege.dk/course/view.php?id=19236

Teacher reported from:
Kenneth Ledet Eduardsen
https://moodle.techcollege.dk/user/profile.php?id=10265

Zendesk task:
https://praxisdigital.zendesk.com/agent/tickets/41179

**Comment by sampraxis** [comment]
@DKSteffensen 
Sadly sharing cart doesn't have any independent capabilities to do the task.
It only rely on Moodle built-in capability.

If we introduce new capabilities, it will become a new feature instead of a bug fix.

**Comment by sampraxis** [comment]
The reason of icon went missing because user doesn't have **moodle/course:update** capability.
Time spent: 2h
