### ISSUE TITLE
Sharing cart redirects to 'frontpage' of a course

### ISSUE THREAD

**Issue by superfoght** [praxisdigital/moodle-block_sharing_cart#77]
When you insert an element from the sharing cart, you are moved to the 'frontpage". It's a bit problematic when using pxgrid, and you are deep down in the section structure and causes the user to have to do extra clicks to return where they were working.

**Comment by AraPraxis** [comment]
It seems to work when you're in sub-sections, on multiple levels down..
After talking with @superfoght we agreed to close the issue and ask the customer if it still occurs..

Closing issue.
