### ISSUE TITLE
Potentially relevant sharing_cart issues

### ISSUE THREAD

**Issue by frederikmillingpytlick** [praxisdigital/moodle-block_sharing_cart#79]
**Potentially relevant issues:**
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/21~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/62~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/67~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/68~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/73~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/78~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/86~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/92~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/120~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/143~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/145~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/153~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/154~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/155~~
- https://github.com/donhinkelman/moodle-block_sharing_cart/issues/157
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/160~~
- ~~https://github.com/donhinkelman/moodle-block_sharing_cart/issues/162~~

**Comment by mcardle** [comment]
In an e-mail from Don he explains he preferably want us to look at issue [#155](https://github.com/donhinkelman/moodle-block_sharing_cart/issues/155) 

```
Hi Ulrik,

Thank you very much for dealing with this urgent request. I appreciate that you were able to incorporate the fixed code.

I agree to close the issue, and hope you will have time to look at issue [#155](https://praxisdigital.zendesk.com/agent/tickets/155) which concerns the question bank. There have been so many changes in the question bank, that I expect issues related to it.  https://github.com/donhinkelman/moodle-block_sharing_cart/issues/155
```

**Comment by Snowdle** [comment]
Issue #155 has been addressed

**Comment by AraPraxis** [comment]
Issue https://github.com/donhinkelman/moodle-block_sharing_cart/issues/145 is tested and the Sharing Cart works fine with the given theme

**Comment by AraPraxis** [comment]
Issue https://github.com/donhinkelman/moodle-block_sharing_cart/issues/67 is sent to our customer team for testing

**Comment by AraPraxis** [comment]
Issue 67 is tested and sent to our release team - A PR has also been requested to donhinkelman

**Comment by AraPraxis** [comment]
Issue https://github.com/donhinkelman/moodle-block_sharing_cart/issues/86 has been researched and a Moodle Tracker issue has been created as Moodle would need to update their way of adding block instances - Further info can be read on the issue

**Comment by AraPraxis** [comment]
I've added 6 new issues (153, 154, 155, 157, 160, 162) and at the moment we're awaiting answers from the users after questions by donhinkelman or the undersigned

**Comment by AraPraxis** [comment]
We've closed all issues because of fixes, missing responses or denied requests..

Only issue 157 is awaiting donhinkelman about multi language error, but we'll look at it at a further time.
Closing issue.
