### ISSUE TITLE
Improve UX of the "Copy whole section" widget in the Sharing cart block view

### ISSUE THREAD

**Issue by AraPraxis** [praxisdigital/moodle-block_sharing_cart#82]
Update the visual display of "Copy whole section", as shown in the issue:
https://github.com/donhinkelman/moodle-block_sharing_cart/issues/67

**Comment by AraPraxis** [comment]
### Test:
That the new setting in sharing cart is working - It should show or hide the "Copy Section" in the bottom of the block
Styling is hereto changed in the "Copy Section" (Refer to 1st and 3rd picture in https://github.com/donhinkelman/moodle-block_sharing_cart/issues/67)

### Info
Version: Moodle 4.0
PR: ara_GH_40-82
Pull: https://github.com/praxisdigital/moodle-block_sharing_cart/pull/83

**Comment by superfoght** [comment]
@AraPraxis it looks and works fine as far as I can tell.

**Comment by AraPraxis** [comment]
Closing issue - Awaiting #86 before release
