### ISSUE TITLE
Multi-Language not working

### ISSUE THREAD

**Issue by AraPraxis** [praxisdigital/moodle-block_sharing_cart#89]
https://github.com/donhinkelman/moodle-block_sharing_cart/issues/157

Multi-Language is not working when copying sections, and we hereto need to test with single activities.

**Comment by frederikmillingpytlick** [comment]
While you are at it, update the readme with the required capabillities

**Capabilities which are checked in block_sharing_cart:**
    moodle/restore:restorecourse
    moodle/restore:restoreactivity
    moodle/backup:backupactivity
    moodle/course:manageactivities

**Specific for copying userdata:**
    moodle/backup:userinfo
    moodle/backup:anonymise
    moodle/restore:userinfo

**Comment by frederikmillingpytlick** [comment]
Fixed in https://github.com/praxisdigital/moodle-block_sharing_cart/pull/138
