### ISSUE TITLE
insert item from sharingcart send you to the frontpage

### ISSUE THREAD

**Issue by Mikkeljeppesen1** [praxisdigital/moodle-block_sharing_cart#91]
courseformat:

if youre in a section and insert an item from sharing cart you will rredirected to the frontpage of the course, and that gives a bad workflow. 

Could it be possible when youre in section and insert an item to stay in the current section or is there a explanation to this behavior.

**Comment by Snowdle** [comment]
Please let me know when this has been tested and approved, so that I can create a PR to the original sharing_cart repository 😄

**Comment by superfoght** [comment]
@Snowdle Works as intended
